services:
  - type: web
    name: wedding-plan-backend
    env: node
    plan: free
    repo: https://github.com/venkatarevathi/wedding-plan.git
    branch: main
    buildCommand: cd backend && npm ci
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production

  - type: static_site
    name: wedding-plan-frontend
    plan: free
    repo: https://github.com/venkatarevathi/wedding-plan.git
    branch: main
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: frontend/dist
